services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - FLASK_APP=web
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./web/static:/app/web/static
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
